-- Money Market Deal Input (staging / maker entry)
CREATE TABLE IF NOT EXISTS MM_NEW_DEAL_INPUT (
    DEAL_ID                         TEXT PRIMARY KEY,
    PRODUCT_ID                      TEXT NOT NULL,
    INSTRUMENT_ID                   TEXT NOT NULL,
    PORTFOLIO_ID                    TEXT NOT NULL,
    DEAL_DATE                       TEXT NOT NULL,
    DEAL_TIME                       TEXT NOT NULL,
    DEALER_ID                       TEXT NOT NULL,
    COUNTERPARTY_ID                 TEXT NOT NULL,
    VALUE_DATE                      TEXT NOT NULL,
    MATURITY_DATE                   TEXT NOT NULL,
    DEAL_TYPE                       TEXT NOT NULL,
    DEPOSIT_TYPE                    TEXT NOT NULL,
    PRICING_TYPE                    TEXT NOT NULL,
    DEAL_CCY                        TEXT NOT NULL,
    PRINCIPAL_AMOUNT                REAL,
    MATURITY_AMOUNT                 REAL,
    INTEREST_BASIS                  TEXT NOT NULL,
    INTEREST_RATE                   REAL,
    SPREAD                          REAL,
    BENCHMARK_ID                    TEXT,
    DAY_COUNT                       TEXT,
    COMPOUNDING_FLAG                INTEGER DEFAULT 0,
    COMPOUND_FREQ                   TEXT,
    FIXING_FREQ                     TEXT,
    SETTLEMENT_FREQ                 TEXT,
    STATUS                          TEXT DEFAULT 'SAVED',
    OUTSTANDING_PRINCIPAL           REAL,
    OUTSTANDING_PRINCIPAL_LCY_EQUIV REAL,
    ACCRUED_INTEREST                REAL,
    ACCRUED_INTEREST_LCY_EQUIV      REAL,
    CREATED_AT                      TEXT DEFAULT (datetime('now')),
    UPDATED_AT                      TEXT DEFAULT (datetime('now'))
);

-- Money Market Deal Master (post-authorization / live book)
CREATE TABLE IF NOT EXISTS MM_DEAL_MASTER (
    DEAL_ID                         TEXT PRIMARY KEY,
    PRODUCT_ID                      TEXT,
    INSTRUMENT_ID                   TEXT,
    PORTFOLIO_ID                    TEXT,
    DEAL_DATE                       TEXT,
    DEAL_TIME                       TEXT,
    DEALER_ID                       TEXT,
    COUNTERPARTY_ID                 TEXT,
    VALUE_DATE                      TEXT,
    MATURITY_DATE                   TEXT,
    DEAL_TYPE                       TEXT,
    DEPOSIT_TYPE                    TEXT,
    PRICING_TYPE                    TEXT,
    DEAL_CCY                        TEXT,
    PRINCIPAL_AMOUNT                REAL,
    MATURITY_AMOUNT                 REAL,
    INTEREST_BASIS                  TEXT,
    INTEREST_RATE                   REAL,
    SPREAD                          REAL,
    BENCHMARK_ID                    TEXT,
    DAY_COUNT                       TEXT,
    COMPOUNDING_FLAG                INTEGER DEFAULT 0,
    COMPOUND_FREQ                   TEXT,
    FIXING_FREQ                     TEXT,
    SETTLEMENT_FREQ                 TEXT,
    STATUS                          TEXT DEFAULT 'VERIFIED',
    OUTSTANDING_PRINCIPAL           REAL,
    OUTSTANDING_PRINCIPAL_LCY_EQUIV REAL,
    ACCRUED_INTEREST                REAL,
    ACCRUED_INTEREST_LCY_EQUIV      REAL,
    CREATED_AT                      TEXT DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                      TEXT DEFAULT CURRENT_TIMESTAMP
);
